name: Build, test and upload coverage

on:
  workflow_call:
    inputs:
      e2e:
        type: boolean
        required: false
        default: false
    secrets:
      token:
        required: false
      token_custom:
        required: false

permissions:
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run checks
        run: pnpm run validate

      - name: Run tests with coverage
        run: pnpm run test:coverage

      - name: Upload coverage to Codecov
        if: github.repository_owner == 'shaftoe'
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true
          use_oidc: true

      - name: Run e2e tests
        if: inputs.e2e == true
        run: pnpm run test:e2e
        env:
          E2E_PROVIDER: ${{ vars.PROVIDER_CUSTOM }}
          E2E_MODEL: ${{ vars.MODEL_CUSTOM }}
          E2E_TOKEN: ${{ secrets.token_custom }}
          E2E_MODEL_CUSTOM: ${{ vars.MODEL_CUSTOM }}
          E2E_PROVIDER_CUSTOM: ${{ vars.PROVIDER_CUSTOM }}
          E2E_TOKEN_CUSTOM: ${{ secrets.token_custom }}
